#!/usr/bin/env python3
"""Generate MAMEComputers/MCMacSoftwareList.h from MAME's Mac floppy lists.

MAME's software lists (hash/mac_flop_orig.xml, mac_flop_clcracked.xml,
mac_flop.xml) record, for many early Mac disks, the SHA-1 of each disk image
and which Mac models the software runs on ("compatibility"). The core looks
a game's disk up by SHA-1 to choose a machine it runs on (see
-catalogueMachines in MAMEComputersGameCore.m).

Usage:
    ./Scripts/generate-mac-software-table.py [MAME source dir]

The MAME source dir defaults to MAMEComputers/deps/mame-active. Run it again
after moving to a newer MAME to pick up new entries.
"""

import os
import sys
import xml.etree.ElementTree as ET

LISTS = ["mac_flop_orig.xml", "mac_flop_clcracked.xml", "mac_flop.xml"]

# MAME machine name -> bit in MCMacMachineMask. Only the machines the core
# offers; "MC68000" in a list means any 68000 Mac. Software for the 68020/030
# colour Macs (Mac II, LC family, Classic II, Color Classic) runs on the
# core's LC II.
LC2 = 16
MACHINES = {
    "mac128k": 1, "mac512k": 2, "mac512ke": 4, "macplus": 8,
    "macii": LC2, "maciix": LC2, "maciicx": LC2, "maciici": LC2, "maciisi": LC2,
    "maclc": LC2, "maclc2": LC2, "maclc3": LC2, "macclas2": LC2, "maccclas": LC2,
    "MC68020": LC2, "MC68020_32": LC2,
}
ANY_68000 = 1 | 2 | 4 | 8


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    mame = sys.argv[1] if len(sys.argv) > 1 else os.path.join(repo, "MAMEComputers", "deps", "mame-active")
    out_path = os.path.join(repo, "MAMEComputers", "MCMacSoftwareList.h")

    entries = {}  # sha1 -> (mask, list name, software name, description)
    for list_name in LISTS:
        path = os.path.join(mame, "hash", list_name)
        root = ET.parse(path).getroot()
        for sw in root.findall("software"):
            compat = [f.get("value", "") for f in sw.findall("sharedfeat") if f.get("name") == "compatibility"]
            if not compat:
                continue
            mask = 0
            for machine in compat[0].split(","):
                machine = machine.strip()
                if machine == "MC68000":
                    mask |= ANY_68000
                mask |= MACHINES.get(machine, 0)
            if mask == 0:
                continue  # only runs on Macs this core doesn't offer
            description = sw.findtext("description", "").strip()
            for rom in sw.iter("rom"):
                sha1 = (rom.get("sha1") or "").lower()
                if len(sha1) == 40 and sha1 not in entries:
                    entries[sha1] = (mask, list_name, sw.get("name"), description)

    lines = [
        "// Generated by Scripts/generate-mac-software-table.py from MAME's",
        "// " + ", ".join(LISTS) + ". Do not edit by hand.",
        "//",
        "// SHA-1 of a Mac disk image -> the Macs MAME's software list says it runs",
        "// on (MCMacMachineMask bits).",
        "",
        "#pragma once",
        "",
        "typedef enum : unsigned char {",
        "    MCMacMachine128K  = 1,",
        "    MCMacMachine512K  = 2,",
        "    MCMacMachine512KE = 4,",
        "    MCMacMachinePlus  = 8,",
        "    MCMacMachineLC2   = 16,",
        "} MCMacMachineMask;",
        "",
        "typedef struct {",
        "    const char *sha1;          // lowercase hex",
        "    unsigned char machines;    // MCMacMachineMask bits",
        "    const char *software;      // MAME software list name",
        "    const char *description;",
        "} MCMacSoftwareEntry;",
        "",
        "// Sorted by sha1, for bsearch.",
        "static const MCMacSoftwareEntry MCMacSoftwareList[] = {",
    ]
    for sha1 in sorted(entries):
        mask, list_name, name, description = entries[sha1]
        lines.append("    { %s, %d, %s, %s }," % (c_string(sha1), mask, c_string(name), c_string(description)))
    lines += ["};", ""]

    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    print("wrote %d disk images to %s" % (len(entries), out_path))


if __name__ == "__main__":
    main()
